CREATE TABLE USERS
(USER_USERNAME VARCHAR(25) NOT NULL,
USER_EMAIL VARCHAR(50) NOT NULL,
USER_PASSWORD VARCHAR(50) NOT NULL,
USER_ACTIVE INT NOT NULL,
USER_WINNINGS INT NOT NULL,
PRIMARY KEY (USER_USERNAME));

CREATE TABLE SPINS
(SPIN_ID UUID DEFAULT RANDOM_UUID(),
SPIN_USERNAME VARCHAR(25) NOT NULL,
SPIN_ROLLERS VARCHAR(50) NOT NULL,
SPIN_BET INT,
SPIN_USERTOKEN VARCHAR(20) NOT NULL,
SPIN_WINSTATUS VARCHAR(10) NOT NULL,
PRIMARY KEY (SPIN_ID));
//FOREIGN KEY (SPIN_USERNAME) REFERENCES USERS(USER_USERNAME));